Private posts permission
topcoder-platform/tc-message-service pull request #100
Opened 2019-05-21 06:12 UTC by maxceem

winning submission from the [challenge 30090720 Topcoder Message Service - Private posts permissions](https://www.topcoder.com/challenges/30090720)

Implemented checking permission for customer users so they cannot access private topics.

For implementation, we used our expression evaluator method, so this functionality is detached from tc-msesage-service logic.

There are few exceptions:
- customer users may still get private topics using endpoint to list topics: `/topics/list?reference=project&referenceId=8031`
- ~customer users may create private topics, even though they cannot access them after~ this is fixed in commit https://github.com/appirio-tech/tc-message-service/pull/100/commits/6c379380a46d04ce8857e807ef128798a0669451.

The left case can be implemented using the expression evaluator method but the way is not perfect. We've started the discussion on the Slack and can continue it on the next issue https://github.com/appirio-tech/tc-message-service/issues/99

2019-05-21 07:20 UTC, vikasrohit approved these changes
Looks good, only thing is that access condition is now getting complicated.

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/attachments/delete.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
Should it be `topic.tags`?

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/attachments/get.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
Should it be `topic.tags`?

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/topics/create.js
> +        const tags = params.tag.split(',');
Just confirming, I think we are still taking `tag` instead of `tags` in payload while we have `tags` in data model, right?

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/topics/get.js
> +        const tags = _.split(dbTopic.tag, ',');
Should it be `dbTopic.tags`?

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/topics/getDb.js
> +            const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(dbTopic.tag, ','),
Should it be `dbTopic.tags`?

2019-05-21 07:20 UTC, vikasrohit commented on app/routes/topics/update.js
> +            const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
Just confirming, I think we are still taking tag instead of tags in payload while we have tags in data model, right?

2019-05-21 07:21 UTC, vikasrohit requested changes
Looks good but access condition now getting complicated.

2019-05-21 10:48 UTC, maxceem commented on app/routes/attachments/get.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
I was also confused by this first. The `topic` object comes from [db.topics.findTopic](https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/attachments/get.js#L60) which uses [adapter.adaptTopics](https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/topics.js#L157) method before returning topics. And that method transforms `tags` array to `tag` string, [here](https://github.com/appirio-tech/tc-message-service/blob/dev/app/services/adapter.js#L93). I believe this is done to be inline with ES index, which we probably didn't want to reindex after updating topics model from `tag` to `tags`.

2019-05-21 10:50 UTC, maxceem commented on app/routes/topics/create.js
> +        const tags = params.tag.split(',');
Right, we send `tag` as a string in payload https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/topics/create.js#L41 while keeping `tags` as an array in DB.

2019-05-21 10:51 UTC, maxceem commented on app/routes/attachments/delete.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
I was also confused by this first. The `topic` object comes from [db.topics.findTopic](https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/attachments/delete.js#L60) which uses [adapter.adaptTopics](https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/topics.js#L157) method before returning topics. And that method transforms `tags` array to `tag` string, [here](https://github.com/appirio-tech/tc-message-service/blob/dev/app/services/adapter.js#L93). I believe this is done to be inline with ES index, which we probably didn't want to reindex after updating topics model from `tag` to `tags`.

2019-05-21 10:57 UTC, maxceem commented on app/routes/topics/get.js
> +        const tags = _.split(dbTopic.tag, ',');
The `dbTopic` object comes from the ES index. And when we put topic to the ES index, we also uses [db.topics.findTopic](https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/indexing/indexing.js#L38) which uses [adapter.adaptTopics](https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/topics.js#L157) method before returning topics. So topics in ES index are saved with a `tag` as a string.

2019-05-21 10:59 UTC, maxceem commented on app/routes/topics/update.js
> +            const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
When we update topic, we cannot change `tag`. The `topic` object comes from the DB using [db.topics.findTopic](https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/topics/update.js#L43) which uses [adapter.adaptTopics](https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/topics.js#L157) method before returning topics. And that method transforms `tags` array to `tag` string, [here](https://github.com/appirio-tech/tc-message-service/blob/dev/app/services/adapter.js#L93).

2019-05-21 11:00 UTC, maxceem commented on app/routes/topics/getDb.js
> +            const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(dbTopic.tag, ','),
The `dbTopic` object comes from the DB using [db.topics.findTopic](https://github.com/appirio-tech/tc-message-service/blob/dev/app/routes/topics/getDb.js#L37) which uses [adapter.adaptTopics](https://github.com/appirio-tech/tc-message-service/blob/dev/app/models/topics.js#L157) method before returning topics. And that method transforms `tags` array to `tag` string, [here](https://github.com/appirio-tech/tc-message-service/blob/dev/app/services/adapter.js#L93).

2019-05-21 11:01 UTC, maxceem commented
> Looks good but access condition now getting complicated.

Yes, it does. Probably we can think about improvements of the expression evaluator method. So we could simplify the access condition.

2019-05-21 11:02 UTC, vikasrohit commented on app/routes/attachments/get.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
Yes, we kept `tag` in the API while we added the support for multiple tags in the model and renamed our database field to `tags`. I think now we are ready to sync `tag` to be `tags` everywhere now.
We don't have to worry about reindexing, as we are not using index for querying any topic. It is just added as support for future usage.

2019-05-21 11:03 UTC, vikasrohit commented on app/routes/attachments/get.js
> +                const hasAccess = await helper.userHasAccessToEntity(userId, hasAccessResp, _.split(topic.tag, ','),
Lets discuss separately for `tag` => `tags`

2019-05-21 11:04 UTC, vikasrohit approved these changes

2019-05-21 11:07 UTC, vikasrohit commented
Do we need a migration script as well to update the access condition?

2019-05-21 11:08 UTC, maxceem commented
@vikasrohit yes, have to run migration script.

2019-05-21 11:10 UTC, vikasrohit commented
I didn't see the migration script in the PR though.

2019-05-21 11:13 UTC, maxceem commented
Oh, my bad forgot to copy the migration script from the submission. Add in the commit https://github.com/appirio-tech/tc-message-service/pull/100/commits/9cfaf444522cecf97390e746c86031fb936d725f

Indeed, have to think about a better way of sharing this repo with the community during the challenges...

2019-05-23 09:39 UTC, vikasrohit commented
@maxceem are we ready to merge this PR?

2019-05-23 12:03 UTC, maxceem commented
@vikasrohit yes, I was about to suggest you the same. Let's merge it, so we can test it longer on DEV before releasing.

2019-05-24 09:58 UTC, merged

2019-05-24 09:58 UTC, vikasrohit commented
Merged @maxceem