Post attachments
topcoder-platform/tc-message-service pull request #94
Opened 2019-04-24 12:28 UTC by gondzo

Do not merge yet

2019-04-26 11:36 UTC, vikasrohit requested changes

2019-04-26 11:36 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
@gondzo why do we need to unset the attachment for the post first?

2019-04-26 11:36 UTC, vikasrohit commented on app/routes/attachments/create.js
> +        const content = createdPostAttachment.toJSON();
@gondzo where are we authorizing the request? I mean, earlier we were calling `callReferenceEndpoint` and `userHasAccessToEntity` methods to check the access to the reference entity. Is it moved to middleware now?

2019-04-26 11:36 UTC, vikasrohit commented on app/routes/attachments/delete.spec.js
> -    describe('for a soft deleted existing attachment', () => {
@gondzo I guess these tests are still valid to be passed except one for `hardDelete` query param if we are not supporting it any more.

2019-04-26 11:36 UTC, vikasrohit commented on app/routes/index.js
> +  router.route(`/${apiVersion}/topics/attachments/:attachmentId`)
I would like to keep the nomenclature consistent here, I mean we should add `/read` for `get` endpoint, `/create` for `post` endpoint and so on.

2019-04-26 11:36 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
Also, should we run this update and next update in a transaction to avoid inconsistent state?

2019-04-26 11:36 UTC, vikasrohit commented on app/routes/posts/update.js
> +      return db.posts.updatePostAttachments(db, postId, attachmentIds)
Can we optimize this call? I mean it would update all the post attachment every time we update post. Can we compare the incoming attachment ids with existing attachments of the post (may be we can take that in request itself and on front end we can pass them from the get request which we made to fetch the post) and check if there is any new attachment to be associated with this post. If there is no attachment to associate with the post, we can skip this call or at least directly resolve the promise without making two further database updates.

2019-04-26 11:36 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
Because we are doing this every time we are updating a topic/post, we are loosing the value of audit field `updatedAt` as it would always be updated with every topic/post update no matter if the actual attachment is updated or not.

2019-04-29 12:01 UTC, gondzo commented on app/models/posts.js
> +     models.post_attachments.update(
if the user want's to remove some attachments from a post, that's done through the update post endpoint - so we first remove all attachments from a post and then re-add the updated ones. It's a bit awkward, but we do need two queries in any case. Transaction is needed here, I'll add that change, and check for updated attachmentIds list

2019-04-29 12:03 UTC, gondzo commented on app/routes/attachments/create.js
> +        const content = createdPostAttachment.toJSON();
no auth for creating an attachment except for checking if the user is logged in - attachment is first created without a link to a post (post is not created yet so there is nothing to link to). Only when the user creates a post we will check permissions with callReferenceEndpoint and userHasAccessToEntity

2019-04-29 12:07 UTC, gondzo commented on app/routes/attachments/delete.spec.js
> -    describe('for a soft deleted existing attachment', () => {
yes, we don't need to differentiate hard/soft delete - all deletes are soft by default and cleanup script will remove unused attachments periodically

2019-04-29 12:08 UTC, gondzo commented on app/routes/index.js
> +  router.route(`/${apiVersion}/topics/attachments/:attachmentId`)
hmm, not very REST-like and not consistent to project service attachments? should we keep it as is or update?

2019-04-29 12:09 UTC, gondzo commented on app/routes/posts/update.js
> +      return db.posts.updatePostAttachments(db, postId, attachmentIds)
yes, we should update `updatePostAttachments` to actually compare the lists and make updates only when necessary

2019-04-30 05:44 UTC, vikasrohit commented on app/routes/attachments/create.js
> +        const content = createdPostAttachment.toJSON();
Okay. May then we need to add some check to stop someone from misusing this endpoint. One check could be that for one `userId` (which we are sure we will have as it is still an authenticated endpoint), we can limit maximum of 20 (configurable via config) non associated posts. I am okay if we you run a separate task for that, but we do need that before going live.

2019-04-30 05:46 UTC, vikasrohit commented on app/routes/attachments/delete.spec.js
> -    describe('for a soft deleted existing attachment', () => {
What I meant here @gondzo is that these tests cases (except the one with `hardDelete` param) should not be deleted.

2019-04-30 05:48 UTC, vikasrohit commented on app/routes/index.js
> +  router.route(`/${apiVersion}/topics/attachments/:attachmentId`)
I don't recall right now the reason to use these extra verbs after the endpoints, however, to be consistent within the same repo, we have to use that for now. We can fix all endpoint together later, if we think these extra verbs are of no use.

2019-04-30 05:52 UTC, vikasrohit commented on app/routes/posts/update.js
> +      return db.posts.updatePostAttachments(db, postId, attachmentIds)
Thanks. Would wait for the updates.

2019-04-30 05:53 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
Thanks.

2019-04-30 09:03 UTC, vikasrohit commented
@gondzo I just merged one more PR for this repo which I guess caused some conflicts now with this PR. Sorry for the trouble. 😬

2019-05-03 09:01 UTC, gondzo commented on app/models/posts.js
> +     models.post_attachments.update(
done

2019-05-03 09:01 UTC, gondzo commented on app/routes/attachments/create.js
> +        const content = createdPostAttachment.toJSON();
done

2019-05-03 09:01 UTC, gondzo commented on app/routes/attachments/delete.spec.js
> -    describe('for a soft deleted existing attachment', () => {
done

2019-05-03 09:01 UTC, gondzo commented on app/routes/index.js
> +  router.route(`/${apiVersion}/topics/attachments/:attachmentId`)
done

2019-05-03 09:01 UTC, gondzo commented on app/routes/posts/update.js
> +      return db.posts.updatePostAttachments(db, postId, attachmentIds)
done

2019-05-03 09:02 UTC, gondzo commented
PR updated and ready for merging (run db migration first)

2019-05-03 09:58 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
Thanks @gondzo However, I am still confused about it. We are first setting `postId` as `null` for all attachments which are `NOT` in `attachmentIds` array and then setting `postId` back to the current `postId` for the attachments represented by `attachmentIds`.

2019-05-03 10:11 UTC, gondzo commented on app/models/posts.js
> +     models.post_attachments.update(
those are two distinct sets - first one is removing attachments from a post (they won't be added again) and the second one is adding new attachments (only those that aren't added yet), so there are no extra updates for any records

2019-05-03 10:26 UTC, vikasrohit commented on app/models/posts.js
> +     models.post_attachments.update(
Got it. Thanks.

2019-05-03 10:27 UTC, vikasrohit commented on app/routes/posts/create.js
> +              id: attachmentIds,
Should we change it to `id: { $in: attachmentIds}`?

2019-05-03 10:50 UTC, gondzo commented on app/routes/posts/create.js
> +              id: attachmentIds,
done

2019-05-03 10:51 UTC, vikasrohit approved these changes

2019-05-03 10:51 UTC, merged