Access condition using evaluate function
topcoder-platform/tc-message-service pull request #95
Opened 2019-04-26 08:46 UTC by maxceem

winning submission from the challenge 30089095 - Topcoder Message Service - Improve access control

At the moment we have 
```js
accessCondition: 'members contains \'{"userId":{userId}}\''
```

And before we run `evaluate` function we should replace `{userId}` with the actual `userId` value. So `{userId}` is currently a common placeholder for all the `accessCondition`s.

2019-04-26 09:33 UTC, vikasrohit requested changes
Overall looks good to me except few minor changes required.

2019-04-26 09:33 UTC, vikasrohit commented on app/models/referenceLookups.js
> +      allowNull: true,
I think we should not allow `null` value here.

2019-04-26 09:33 UTC, vikasrohit commented on app/services/helper.js
> +        return hasAccess;
After placing `not null` constraint, we won't have this situation, however, I would like to return false if there is no `accessCondition` found for the given reference. We can always pass `1 == 1` for the cases where we just need to have the reference endpoint return 200 to validate the access.

2019-04-26 09:33 UTC, vikasrohit commented on app/services/helper.js
> +      const { accessCondition } = await db.reference_lookups.findOne({ where: { reference } });
Can we easily get rid of calling this twice? We are calling this once in `callReferenceEndpoint` method just before calling this one. If it is not trivial, lets leave as is.

2019-04-29 05:33 UTC, maxceem commented on app/services/helper.js
> +      const { accessCondition } = await db.reference_lookups.findOne({ where: { reference } });
@vikasrohit this would require refactoring and combining methods `callReferenceEndpoint` and `userHasAccessToEntity` together into one. Otherwise, we can add it to the output from `callReferenceEndpoint` which would be hacky, especially as we wanted to decouple these two methods initially.

Maybe we can plan a refactoring for this issue if you like.

2019-04-30 02:50 UTC, maxceem commented
@vikasrohit 

I've added one more commit fixing 2 out of 3 comments.

The only one thing I propose to skip for now is this:
> Can we easily get rid of calling this twice? We are calling this once in callReferenceEndpoint method just before calling this one. If it is not trivial, lets leave as is.

Refer the comment for details.

Let me know if anything left.

2019-04-30 06:27 UTC, vikasrohit commented on app/services/helper.js
> +      const { accessCondition } = await db.reference_lookups.findOne({ where: { reference } });
I think we are good for now.

2019-04-30 06:28 UTC, vikasrohit commented
Thanks for the updates @maxceem. PR looks good to me now.

2019-04-30 06:28 UTC, vikasrohit approved these changes

2019-04-30 06:28 UTC, merged

2019-05-02 06:25 UTC, vikasrohit commented
Referencing the issue #91